version: '3.4'

services:
  apprunnerpoc:
    image: apprunnerpoc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
